# Generated by Django 4.0.4 on 2022-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_produto_centrocusto_remove_produto_descri'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='email_resp',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
