# Generated by Django 4.0.4 on 2022-04-20 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_responsavel_email_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoproduto',
            name='dataIInsercao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
