# Generated by Django 4.0.4 on 2022-04-20 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_transacaoproduto_dataiinsercao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaosucata',
            name='dataInser',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
