# Generated by Django 4.0.4 on 2022-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transacaosucata_datainser'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoproduto',
            name='user_Salva',
            field=models.CharField(blank=True, default='Admin', max_length=15),
        ),
        migrations.AddField(
            model_name='transacaosucata',
            name='user',
            field=models.CharField(blank=True, default='Admin', max_length=15),
        ),
    ]
